In [1]:
# 기본 패키지 불러오기 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
plt.style.use("seaborn")
sns.set(font_scale=1)
sns.set_style("whitegrid")

# 그래프를 노트북 안에 그리기 위해 설정
%matplotlib inline

# 맥 OS 폰트 깨짐 방지 코드
from matplotlib import rc
import matplotlib as mpl 
import matplotlib.font_manager as fm 

rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

## Inside Airbnb: London Data

### 컬럼 속성 이해

In [2]:
london_lists_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/listings.csv')
london_lists_summary_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/listings_outline.csv')
london_neighbourhoods_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/neighbourhoods.csv')
london_reviews_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/reviews.csv')
london_reviews_summary_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/reviews_outline.csv')

In [3]:
london_lists = london_lists_raw.copy()
london_lists

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,312761,https://www.airbnb.com/rooms/312761,20240319050633,2024-03-21,city scrape,Spacious Central London Apartment by Hoxton Sq...,"Very central location, in the middle of Shored...",Everything is so convenient and the area is al...,https://a0.muscache.com/pictures/miso/Hosting-...,1608226,...,5.00,4.89,4.93,NaN,f,1,1,0,0,0.86
1,13913,https://www.airbnb.com/rooms/13913,20240319050633,2024-03-20,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.83,4.70,4.70,NaN,f,3,2,1,0,0.25
2,15400,https://www.airbnb.com/rooms/15400,20240319050633,2024-03-20,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.83,4.93,4.74,NaN,f,1,1,0,0,0.54
3,159736,https://www.airbnb.com/rooms/159736,20240319050633,2024-03-20,city scrape,A double Room 5mins from King's College Hospital,Calm sunny double room with a queen size bed a...,We love that in Loughborough Junction we live ...,https://a0.muscache.com/pictures/1067303/d2300...,766056,...,4.89,4.34,4.66,NaN,f,4,0,4,0,0.62
4,165336,https://www.airbnb.com/rooms/165336,20240319050633,2024-03-21,city scrape,Charming Flat in Notting Hill,A stylish apartment close to Portobello market...,"Notting Hill has many cafes, bars and restaura...",https://a0.muscache.com/pictures/60757460/47f8...,761400,...,4.96,4.87,4.71,NaN,f,1,1,0,0,1.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90847,1115272743905612628,https://www.airbnb.com/rooms/1115272743905612628,20240319050633,2024-03-19,city scrape,Primrose Hill Studio #25,A place to spread out in with extra wiggle roo...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,565833376,...,NaN,NaN,NaN,NaN,t,48,48,0,0,NaN
90848,1115272767893608505,https://www.airbnb.com/rooms/1115272767893608505,20240319050633,2024-03-19,city scrape,Primrose Hill Studio #27,"Two-storey living, unwind downstairs and rest ...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,565833376,...,NaN,NaN,NaN,NaN,t,48,48,0,0,NaN
90849,1115285644506865913,https://www.airbnb.com/rooms/1115285644506865913,20240319050633,2024-03-21,city scrape,Quad Bedroom with External Bathroom,The Chapter Hotels group had been in the hotel...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,444801189,...,NaN,NaN,NaN,NaN,t,33,10,23,0,NaN
90850,1115338006572763275,https://www.airbnb.com/rooms/1115338006572763275,20240319050633,2024-03-20,city scrape,Grosvenor Collection,This bright and spacious three-bedroom penthou...,"The area itself is a vibrant neighbourhood, of...",https://a0.muscache.com/pictures/prohost-api/H...,514234035,...,NaN,NaN,NaN,NaN,t,52,51,1,0,NaN
90851,1115347885713265376,https://www.airbnb.com/rooms/1115347885713265376,20240319050633,2024-03-19,city scrape,Comfy Home - Wood Green,Great for families and groups travelling toget...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,215155525,...,NaN,NaN,NaN,NaN,t,2,2,0,0,NaN

In [4]:
london_lists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90852 entries, 0 to 90851
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            90852 non-null  int64
 1   listing_url                                   90852 non-null  object
 2   scrape_id                                     90852 non-null  int64
 3   last_scraped                                  90852 non-null  object
 4   source                                        90852 non-null  object
 5   name                                          90852 non-null  object
 6   description                                   87851 non-null  object
 7   neighborhood_overview                         47521 non-null  object
 8   picture_url                                   90842 non-null  object
 9   host_id                                       90852 non-null  int64
 10  host_url                                      90852 non-null  object
 11  host_name                                     90847 non-null  object
 12  host_since                                    90847 non-null  object
 13  host_location                                 70566 non-null  object
 14  host_about                                    46814 non-null  object
 15  host_response_time                            57797 non-null  object
 16  host_response_rate                            57797 non-null  object
 17  host_acceptance_rate                          65213 non-null  object
 18  host_is_superhost                             90463 non-null  object
 19  host_thumbnail_url                            90847 non-null  object
 20  host_picture_url                              90847 non-null  object
 21  host_neighbourhood                            46955 non-null  object
 22  host_listings_count                           90847 non-null  float64
 23  host_total_listings_count                     90847 non-null  float64
 24  host_verifications                            90852 non-null  object
 25  host_has_profile_pic                          90847 non-null  object
 26  host_identity_verified                        90847 non-null  object
 27  neighbourhood                                 47522 non-null  object
 28  neighbourhood_cleansed                        90852 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      90852 non-null  float64
 31  longitude                                     90852 non-null  float64
 32  property_type                                 90852 non-null  object
 33  room_type                                     90852 non-null  object
 34  accommodates                                  90852 non-null  int64
 35  bathrooms                                     57894 non-null  float64
 36  bathrooms_text                                90722 non-null  object
 37  bedrooms                                      78118 non-null  float64
 38  beds                                          57837 non-null  float64
 39  amenities                                     90852 non-null  object
 40  price                                         57885 non-null  object
 41  minimum_nights                                90852 non-null  int64
 42  maximum_nights                                90852 non-null  int64
 43  minimum_minimum_nights                        90851 non-null  float64
 44  maximum_minimum_nights                        90851 non-null  float64
 45  minimum_maximum_nights                        90851 non-null  float64
 46  maximum_maximum_nights                        90851 non-null  float64
 47  minimum_nights_avg_ntm                        90851 non-null  float64
 48  maximum_nights_avg_ntm                        90851 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              86773 non-null  object
 51  availability_30                               90852 non-null  int64
 52  availability_60                               90852 non-null  int64
 53  availability_90                               90852 non-null  int64
 54  availability_365                              90852 non-null  int64
 55  calendar_last_scraped                         90852 non-null  object
 56  number_of_reviews                             90852 non-null  int64
 57  number_of_reviews_ltm                         90852 non-null  int64
 58  number_of_reviews_l30d                        90852 non-null  int64
 59  first_review                                  65869 non-null  object
 60  last_review                                   65869 non-null  object
 61  review_scores_rating                          65869 non-null  float64
 62  review_scores_accuracy                        65838 non-null  float64
 63  review_scores_cleanliness                     65843 non-null  float64
 64  review_scores_checkin                         65808 non-null  float64
 65  review_scores_communication                   65833 non-null  float64
 66  review_scores_location                        65808 non-null  float64
 67  review_scores_value                           65806 non-null  float64
 68  license                                       0 non-null      float64
 69  instant_bookable                              90852 non-null  object
 70  calculated_host_listings_count                90852 non-null  int64
 71  calculated_host_listings_count_entire_homes   90852 non-null  int64
 72  calculated_host_listings_count_private_rooms  90852 non-null  int64
 73  calculated_host_listings_count_shared_rooms   90852 non-null  int64
 74  reviews_per_month                             65869 non-null  float64
dtypes: float64(24), int64(17), object(34)
memory usage: 52.0+ MB

In [5]:
london_lists.columns.to_frame().reset_index(drop=True).rename(columns={0:'column name'}).to_csv('./NameofColumns_rawdata.csv')

In [6]:
london_lists.host_verifications.unique()

array(["['email', 'phone']", "['phone']",
       "['email', 'phone', 'work_email']", "['email']", '[]',
       "['phone', 'work_email']", "['email', 'phone', 'photographer']",
       'None', "['email', 'work_email']"], dtype=object)

### host_identity_verified 컬럼

In [7]:
# 호스트 신원 검증 여부 컬럼의 유니크 값 확인 
london_lists.host_identity_verified.unique()

array(['t', 'f', nan], dtype=object)

In [8]:
# 전체 행 개수 확인 : 90,852개
print(london_lists.shape)
print()

# 호스트의 신원이 검증된 숙소의 개수 : 79,553개
host_identity_verified_t = london_lists.host_identity_verified == 't'
print(london_lists[host_identity_verified_t].shape)
print()

# 호스트의 신원이 검증되지 않은 숙소의 개수 : 11,294개
host_identity_verified_f = london_lists.host_identity_verified == 'f'
print(london_lists[host_identity_verified_f].shape)
print()

# 신원 검증 여부가 null값인 개수 : 5개 
print(london_lists.host_identity_verified.isnull().sum())
print()

# 누락 여부 확인 : 누락 없음
79553 + 11294 + 5

(90852, 75)

(79553, 75)

(11294, 75)

5

90852

neighbourhood /neighbourhood_cleansed /neighbourhood_group_cleansed 컬럼

In [9]:
# neighbourhood: 숙소가 위치한 넓은 지역명 컬럼 유니크값 확인 

london_lists.neighbourhood.unique()

array(['London, England, United Kingdom',
       'Islington, Greater London, United Kingdom',
       'London, United Kingdom', 'Lambeth, England, United Kingdom',
       'Kensington, England, United Kingdom', nan,
       'Greater London, England, United Kingdom',
       'London, Fitzrovia, United Kingdom',
       " St Margaret's, Isleworth, Middlesex, United Kingdom",
       'Richmond, United Kingdom', 'Paddington, England, United Kingdom',
       'Oval, London, United Kingdom', 'East Finchley, United Kingdom',
       'Enfield, United Kingdom', 'Fulham, London, United Kingdom',
       'Chingford, London, United Kingdom',
       'Richmond, England, United Kingdom',
       'Hounslow, Greater London, United Kingdom',
       'Hackney, London, United Kingdom',
       'Barking, London, United Kingdom',
       'Walthamstow, Greater London, United Kingdom',
       'Kensington, Greater London, United Kingdom',
       'Islington, London, United Kingdom',
       'London, Greater London, United Kingdom',
       'Hackney, England, United Kingdom',
       'Tottenham, England, United Kingdom',
       'Camden Town, England, United Kingdom',
       'Lewisham, England, United Kingdom',
       'Walthamstow, England, United Kingdom',
       'Camberwell, England, United Kingdom', 'Morden, United Kingdom',
       'Wandsworth, United Kingdom', 'Thornton Heath, United Kingdom',
       'Wandsworth, England, United Kingdom',
       'Greenwich, England, United Kingdom',
       'Enfield, England, United Kingdom',
       'East Ham, England, United Kingdom',
       'Feltham, England, United Kingdom',
       'Greater London, United Kingdom',
       'Islington, England, United Kingdom',
       'Hammersmith, England, United Kingdom', 'Poplar, United Kingdom',
       'Highgate, London , England, United Kingdom',
       'Merton, England, United Kingdom', 'Orpington, United Kingdom',
       'Camden Town, Greater London, United Kingdom',
       'London, Hampstead, United Kingdom',
       'Ealing, England, United Kingdom',
       'Hammersmith, London, United Kingdom',
       'Muswell Hill, London, United Kingdom',
       'London, Walthamstow, United Kingdom',
       'Walthamstow, London, United Kingdom', 'Chiswick, United Kingdom',
       'Wimbledon, London, United Kingdom',
       'Greater London , England, United Kingdom',
       'Uxbridge, United Kingdom', 'teddington, middx, United Kingdom',
       'wimbledon, London, United Kingdom',
       'Isleworth, Middx, United Kingdom', 'Mitcham, United Kingdom',
       'Hackney, United Kingdom', 'Romford, United Kingdom',
       'London, SW, United Kingdom', 'Morden, Surrey, United Kingdom',
       'Limehouse , United Kingdom', 'London, Loomsbury, United Kingdom',
       'Harrow, United Kingdom', 'Lambeth, United Kingdom',
       'England, United Kingdom',
       'Enfield, Greater London, United Kingdom',
       'Greenford (London), UK, United Kingdom',
       'Hoxton, London, United Kingdom', 'London, N1 0ju, United Kingdom',
       'Mildmay Ward, Islington, London, United Kingdom',
       'Kingston upon Thames, United Kingdom',
       'London, Uk, United Kingdom', 'London, U.K., United Kingdom',
       'Woodford Green, United Kingdom',
       'London, Kensington Olympia, United Kingdom',
       'West Hampstead, London, United Kingdom',
       'Northolt, United Kingdom', 'Bromley, United Kingdom',
       'Ilford, United Kingdom',
       'Hammersmith London, England, United Kingdom',
       'Hayes, United Kingdom', 'Hounslow, United Kingdom',
       'Finsbury Park, London, United Kingdom',
       'Fulham, London, England, United Kingdom',
       'London , Acton, United Kingdom', 'Central London, United Kingdom',
       'London Borough of Islington, England, United Kingdom',
       'Twickenham, United Kingdom', 'Croydon, United Kingdom',
       'London, Harringay, United Kingdom',
       'Hampton Wick, Greater London, United Kingdom',
       'Isleworth, United Kingdom', 'London, UK, United Kingdom',
       'London, Kentish Town, United Kingdom',
       'London, stoke newington, United Kingdom',
       'Westminster, London, United Kingdom',
       'London Borough of Redbridge, England, United Kingdom',
       'London, Pimlico, United Kingdom',
       'Marylebone, London, United Kingdom',
       'STEPNEY GREEN, LONDON, United Kingdom',
       'Teddington , Middlesex, United Kingdom',
       'London, Marylebone, United Kingdom',
       'Common, London, United Kingdom',
       ' Maida Vale, London, United Kingdom',
       'London, Chiswick, United Kingdom', 'Brentford, United Kingdom',
       'Chislehurst, England, United Kingdom',
       'Northolt, middlesex, United Kingdom',
       'Bow, London, United Kingdom',
       'London, Tower hamlets, United Kingdom',
       'Water Gardens Square, United Kingdom',
       'London, LONDON, United Kingdom',
       'Central London, London, United Kingdom',
       'West Wickham , Kent, United Kingdom',
       'New Barnet, United Kingdom',
       'London, Westminster, United Kingdom',
       'London, Great Britain, United Kingdom',
       'London Borough of Southwark, England, United Kingdom',
       'Bermondsey, London, United Kingdom',
       'West Drayton, London, United Kingdom',
       'Notting hill , England, United Kingdom',
       'Kilburn, London, Greater London, United Kingdom',
       'London , Greater London, United Kingdom',
       'London Borough of Hackney, England, United Kingdom',
       'London, Battersea, United Kingdom',
       'London Borough of Haringey, England, United Kingdom',
       'Stoke Newington, London, United Kingdom',
       'London, Bethnal green, United Kingdom',
       'Hampstead, United Kingdom',
       'Greater London, London, United Kingdom',
       'Brixton, London, United Kingdom',
       'Richmond, Surrey, United Kingdom',
       'Greater London, London , United Kingdom',
       'Greater London, london, United Kingdom',
       'London, WALTHAMSTOW, United Kingdom', 'Sutton, United Kingdom',
       'London, Finsbury Park, United Kingdom',
       'West Kensington, London, United Kingdom',
       ' london, leytonstone, United Kingdom',
       'Greater London, West Kensington, United Kingdom',
       'City Of London, London, United Kingdom', 'Pinner, United Kingdom',
       'London Borough of Camden, England, United Kingdom',
       'Shirley, Croydon, England, United Kingdom',
       'Barnet, England, United Kingdom',
       'London, london, United Kingdom', ' London, United Kingdom',
       'Wallington, United Kingdom',
       'Putney, Greater London, United Kingdom',
       'Londra, Greater London, United Kingdom',
       'Balham , London, United Kingdom',
       'Kentish Town, London, United Kingdom',
       'Poplar , London, United Kingdom',
       'Chiswick, London, United Kingdom',
       'Shoreditch, London, United Kingdom',
       'London Borough of Camden, United Kingdom',
       'London, ENFIELD, United Kingdom',
       'South Kensington, London, United Kingdom',
       'Beckenham, United Kingdom', 'Carshalton, United Kingdom',
       'Clapham, London, United Kingdom',
       'Hampstead, England, United Kingdom',
       'Tower Hamlets, London, Greater London, United Kingdom',
       'London, Maida Vale, United Kingdom',
       'Peckham, London, United Kingdom',
       'Canonbury, London, United Kingdom', 'Brixton, United Kingdom',
       'London, Peckham, United Kingdom',
       'Richmond, Greater London, United Kingdom',
       'London, Wimbledon Park, United Kingdom',
       'Twickenham, Greater London, United Kingdom',
       'South Bermondsey, London, United Kingdom',
       'London, Dalston, United Kingdom',
       'Wood Green, London, United Kingdom',
       'Nunhead, London, United Kingdom',
       'London, Central London, United Kingdom',
       'Chelsea, London, United Kingdom',
       'Hackney, Greater London, United Kingdom',
       'London, Central London Zone 1 (Regents Park), United Kingdom',
       'London, Hackney London Fields and Broadway Market, United Kingdom',
       'London, Islington, United Kingdom',
       'Morden, Greater London, United Kingdom',
       'London , London, United Kingdom',
       'London Borough of Barking and Dagenham, England, United Kingdom',
       'Putney, London, United Kingdom',
       'Purley, Greater London, United Kingdom',
       'Londyn, LONDON, United Kingdom',
       'Battersea, London, United Kingdom',
       'Hannibal Road, London, United Kingdom',
       'London, Southwark, United Kingdom',
       'Wembley, Middlesex, United Kingdom',
       'London, Hobbs place estate, United Kingdom',
       'Earlsfield, London, United Kingdom',
       'London, Hammersmith, United Kingdom',
       'Brixton, England, United Kingdom',
       'chelsea /london, Greater London, United Kingdom',
       'Londyn, Anglia, United Kingdom',
       'Richmond Upon Thames, Greater London, United Kingdom',
       "Duckett's Green, London, United Kingdom",
       'Feltham, United Kingdom', 'Purley, England, United Kingdom',
       'London, Chelsea, United Kingdom',
       'Londres, Grand Londres, United Kingdom',
       'Brent, England, United Kingdom',
       'Hackney , London, United Kingdom',
       'London Fields , Hackney, United Kingdom',
       'London,  , United Kingdom',
       'London, Tower Hamlets, United Kingdom', 'Londra, United Kingdom',
       'United Kingdom', 'London , England, United Kingdom',
       'Whitechapel , London, United Kingdom',
       'Wallington, Surrey, United Kingdom', 'Mayfair, United Kingdom',
       'London, Camden, United Kingdom',
       'Kingston upon Thames, England, United Kingdom',
       'kennington, United Kingdom',
       'Isleworth, Middlesex, United Kingdom',
       'Greenford, Greater London, United Kingdom',
       'Putney, London, Greater London, United Kingdom',
       'London, CROYDON-NORBURY, United Kingdom',
       'London, Edmonton, United Kingdom',
       'London, South West London, United Kingdom',
       'Colindale, London, United Kingdom',
       'Tufnell Park, London, United Kingdom',
       'London Borough of Croydon, England, United Kingdom',
       'Greenwich, London, United Kingdom', 'london, United Kingdom',
       'Brentford, England, United Kingdom',
       'London Borough of Wandsworth, England, United Kingdom',
       'Croydon, Greater London, United Kingdom',
       'Vauxhall, Greater London, United Kingdom',
       'Richmond, London, United Kingdom',
       'Shirley, Croydon, Greater London, United Kingdom',
       'Streatham, London, United Kingdom',
       'Camberwell, London, United Kingdom',
       'Feltham, Greater London, United Kingdom',
       'New Malden, London, United Kingdom',
       'London Borough of Lewisham, England, United Kingdom',
       'Teddington, Greater London, United Kingdom',
       'Stratford London, United Kingdom',
       'Notting Hill, London, United Kingdom',
       'Central, England, United Kingdom',
       'Muswell Hill, London, England, United Kingdom',
       'London, Clapham, United Kingdom', 'Edgware, United Kingdom',
       'Kilburn, London, United Kingdom',
       'West Drayton, Greater London, United Kingdom',
       'Ealing, London, United Kingdom', 'London, NA, United Kingdom',
       'Hampton, United Kingdom', 'London, Kennington, United Kingdom',
       'Beckenham, Greater London, United Kingdom',
       'Londres, Greater London, United Kingdom',
       'London, Highgate, United Kingdom',
       'Surbiton, Surrey, United Kingdom',
       'Croydon, London, United Kingdom',
       'Romford, Essex, United Kingdom',
       'London, Wandsworth, United Kingdom',
       'London, Newham, United Kingdom',
       'Whitton, Twickenham, United Kingdom',
       'Worcester Park, United Kingdom', 'London , UK, United Kingdom',
       'Twickenham, Mddx, United Kingdom',
       'Wimbledon, Greater London, United Kingdom',
       'East Dulwich, London, United Kingdom',
       'New Malden, Greater London, United Kingdom',
       'Barking, United Kingdom', 'Westerham, Kent, United Kingdom',
       'London Borough of Tower Hamlets, England, United Kingdom',
       'London, GREATER LONDON, United Kingdom',
       'Ruislip, England, United Kingdom',
       'Walthamstow Village, London, United Kingdom',
       'Southfields, London, England, United Kingdom',
       'London, Londojn, United Kingdom',
       'Mitcham, London, United Kingdom',
       'Ealing, london, United Kingdom', 'Teddington, United Kingdom',
       'Hampton,  , United Kingdom',
       'Greater London, Woolwich, United Kingdom',
       'Kingston upon Thames, Greater London, United Kingdom',
       'Londres, London, United Kingdom',
       'Twickenham, Middlesex, United Kingdom',
       'East Dulwich, London, England, United Kingdom',
       'Mill Hill, United Kingdom',
       'Worcester Park, Greater London, United Kingdom',
       'London, London Borough of Harringay, United Kingdom',
       'London, South Woodford, United Kingdom',
       'South Croydon, England, United Kingdom',
       'GreaterLondon, England, United Kingdom',
       'London, Dulwich, United Kingdom',
       'London Borough of Hammersmith and Fulham, England, United Kingdom',
       'London , Maida Vale, United Kingdom',
       'Uxbridge, Middlesex, United Kingdom',
       'London, hackney, United Kingdom',
       'Harrow, London, United Kingdom',
       'Central London, England, United Kingdom',
       'London, Crouch End, United Kingdom',
       'Edmonton, London, United Kingdom',
       'Haringey, London, United Kingdom',
       'London, islington, United Kingdom',
       'London, central london, United Kingdom',
       'Surbiton, United Kingdom', 'Londres, Angleterre, United Kingdom',
       'Hampton, Greater London, United Kingdom',
       'Nunhead , London, United Kingdom',
       'London, Hackney, United Kingdom',
       'London Borough of Waltham Forest, England, United Kingdom',
       'South Croydon, United Kingdom',
       'Shooters Hill, UK, United Kingdom',
       'London, greater London, United Kingdom',
       'East Barnet, London, United Kingdom',
       'London, UK, London, United Kingdom',
       'Ilford, England, United Kingdom',
       'Royal Borough of Kensington and Chelsea, England, United Kingdom',
       'Westminster , London, United Kingdom',
       'London, ealing, United Kingdom', 'Londres, GB, United Kingdom',
       'London, Fulham, United Kingdom',
       'St Mary Cray, Orpington, United Kingdom',
       'London , -, United Kingdom', 'London, ENGLAND, United Kingdom',
       'London Borough of Brent, England, United Kingdom',
       'London, London, City of, United Kingdom',
       'London, Maida vale, United Kingdom',
       'Belvedere, Greater London, United Kingdom',
       'Lucas Close, United Kingdom',
       'London, Canary Wharf - Tower Hamlets, United Kingdom',
       'Wimbledon, United Kingdom', 'Hornchurch, Essex, United Kingdom',
       'London, Central london, United Kingdom',
       'West Norwood, London, United Kingdom',
       'London, W4., United Kingdom', 'london, battersea, United Kingdom',
       'Balham, London, United Kingdom', 'London, N/a, United Kingdom',
       'Southall, London, United Kingdom',
       'London Borough of Ealing, England, United Kingdom',
       'Southall, MIDDLESEX, United Kingdom',
       'Harrow, Greater London, United Kingdom',
       'Twickenham, England, United Kingdom',
       'Barnes, London, United Kingdom',
       'East Molesey, Surrey, United Kingdom',
       'Ilford, Essex, United Kingdom', 'Orpington, Kent, United Kingdom',
       'Wembley Park, Greater London, United Kingdom',
       'Orpington, England, United Kingdom',
       'London, London, United Kingdom, United Kingdom',
       'London, City of London, United Kingdom',
       'New Eltham, United Kingdom', 'London, Middlesex, United Kingdom',
       'Sanderstead, South Croydon , Greater London, United Kingdom',
       'Stanmore, United Kingdom',
       'London, Non-USA Province, United Kingdom',
       'Ealing Broadway, London, United Kingdom',
       'Isleworth, London, United Kingdom',
       'Isleworth, Greater London, United Kingdom',
       'Loraine Estate , London, United Kingdom',
       'Surbiton, England, United Kingdom',
       'Stratford, London, United Kingdom',
       'Brentford, Greater London, United Kingdom',
       'London, Surrey, United Kingdom',
       'Twickenham, N/A, United Kingdom',
       'Battersea Park London, England, United Kingdom',
       'Kingston upon Thames, Surrey, United Kingdom',
       'Bromley, Greater London, United Kingdom',
       'Southfields Wimbledon, London, United Kingdom',
       'Clerkenwell, London , United Kingdom',
       'Clerkenwell, United Kingdom', 'New Malden, United Kingdom',
       'Hounslow, London, United Kingdom',
       'Teddington, Middlesex, United Kingdom', 'Acton, United Kingdom',
       'Wembley, London, United Kingdom',
       'Bromley, England, United Kingdom',
       'Richmond, Middlesex, United Kingdom',
       'Woordford Green, Greater London, United Kingdom',
       'Romford, England, United Kingdom',
       'London, harringay, United Kingdom',
       'Mayfair, London, United Kingdom', 'London, U.K, United Kingdom',
       'Hampton Wick, United Kingdom', 'West Drayton, United Kingdom',
       'London, GB, United Kingdom',
       'Clapham Road Estate, United Kingdom',
       'Barnet, Greater London, United Kingdom',
       'Barking, England, United Kingdom',
       "Queen's Park / London, United Kingdom",
       'London, uk, United Kingdom', 'Wimbledon, England, United Kingdom',
       'London, middlesex, United Kingdom',
       'Greenwich , Greater London, United Kingdom',
       'London , Dalston square, United Kingdom',
       'London Silvertown, United Kingdom', 'Talbot Yard, United Kingdom',
       'Limehouse, London, United Kingdom',
       'Forest Hill, London, United Kingdom',
       'London, The, United Kingdom', 'Bermondsey, United Kingdom',
       'New Barnet, England, United Kingdom',
       'Saint Margarets, England, United Kingdom',
       'Cranston Estate, United Kingdom',
       'London, Greenwich, United Kingdom',
       'London, Kilburn, United Kingdom',
       'Clerkenwell, London, United Kingdom',
       'London, Dollis Hill/Willesden, United Kingdom',
       'London, Wembley, United Kingdom', 'Southall, United Kingdom',
       'Kensington, London, United Kingdom',
       'Greater London, shadwell, United Kingdom',
       'Mitcham, Greater London, United Kingdom',
       'Kenley, United Kingdom', 'London , london, United Kingdom',
       'Orpington, Greater London, United Kingdom',
       'Biggin Hill, England, United Kingdom',
       'Barking, Greater London, United Kingdom',
       'West Drayton, England, United Kingdom', 'Wembley, United Kingdom',
       'South Kensington Station, London, United Kingdom',
       'London, Greenwich - Deptford, United Kingdom',
       'London, Shoreditch, United Kingdom',
       'Queensway, London, United Kingdom',
       'Hampton Hill, United Kingdom', 'Beckenham, Kent, United Kingdom',
       'notting hill, london, United Kingdom',
       'London, Hendon, United Kingdom', 'FULHAM, London, United Kingdom',
       'Sutton, Greater London, United Kingdom',
       'kingsbury, london, Greater London, United Kingdom',
       'Londres, Islington, United Kingdom',
       'Battersea, England, United Kingdom',
       'Enfield, London, United Kingdom', 'Long Ditton, United Kingdom',
       'London, Haringey, United Kingdom',
       'London, Queens Park, United Kingdom',
       'Wimbledon , London, United Kingdom',
       'London, United kingdom, United Kingdom',
       'Belvedere, United Kingdom', 'Londres, United Kingdom',
       'Sidcup, Kent, United Kingdom', 'London, catford, United Kingdom',
       'Colindale, Greater London, United Kingdom',
       'London, East Dulwich, United Kingdom',
       'Londres,  , United Kingdom', 'London, N/A, United Kingdom',
       'central  London , England, United Kingdom',

In [10]:
# neighbourhood 컬럼의 유니크한 값 개수 확인 및 null 값 개수 확인 
print(london_lists.neighbourhood.nunique())
print(london_lists.neighbourhood.isnull().sum())

865
43330

In [11]:
# neighbourhood_cleansed의 유니크값 확인

london_lists.neighbourhood_cleansed.unique()

array(['Hackney', 'Islington', 'Kensington and Chelsea', 'Lambeth',
       'Brent', 'Southwark', 'Westminster', 'Wandsworth', 'Tower Hamlets',
       'Richmond upon Thames', 'Newham', 'Camden', 'Haringey', 'Enfield',
       'Hammersmith and Fulham', 'Waltham Forest', 'Barnet', 'Hounslow',
       'Barking and Dagenham', 'Croydon', 'Lewisham', 'Ealing', 'Merton',
       'City of London', 'Havering', 'Greenwich', 'Hillingdon', 'Bromley',
       'Redbridge', 'Harrow', 'Bexley', 'Kingston upon Thames', 'Sutton'],
      dtype=object)

In [12]:
# neighbourhood_cleansed의 유니크값 개수 확인 및 null값 개수 확인

print(london_lists.neighbourhood_cleansed.nunique())
print(london_lists.neighbourhood_cleansed.isnull().sum())

33
0

In [13]:
# neighbourhood_group_cleansed의 null 값 개수 확인 

london_lists.neighbourhood_group_cleansed.isnull().sum()

90852

* neighbourhood 컬럼 유니크값이 865개로 지역별 데이터를 바탕으로한 인사이트를 얻기 어려움 
* neighbourhood_group_cleansed 행 전체가 null값 >> 로우 데이터에서도 삭제하는 것이 좋을 것.

<br />

* neighbourhood_cleansed 컬럼이 유니크값이 33개로 그나마 지역별 인사이트를 얻는 데 유용할 것.

### property_type 관련 컬럼

In [14]:
london_lists.property_type.unique()

array(['Entire rental unit', 'Private room in rental unit',
       'Entire townhouse', 'Entire home', 'Private room in home',
       'Entire guesthouse', 'Private room in townhouse', 'Entire condo',
       'Private room in condo', 'Room in serviced apartment',
       'Room in aparthotel', 'Entire serviced apartment',
       'Private room in loft', 'Private room',
       'Private room in bed and breakfast', 'Entire guest suite',
       'Houseboat', 'Private room in serviced apartment',
       'Private room in bungalow', 'Private room in guesthouse',
       'Shared room in home', 'Entire loft', 'Entire cabin',
       'Private room in yurt', 'Boat', 'Shared room in condo',
       'Private room in guest suite', 'Entire cottage',
       'Private room in villa', 'Private room in cottage', 'Tiny home',
       'Entire place', 'Private room in houseboat', 'Shared room in loft',
       'Room in bed and breakfast', 'Shared room in rental unit',
       'Private room in casa particular', 'Shepherd’s hut',
       'Private room in vacation home', 'Room in boutique hotel',
       'Shared room', 'Shared room in bungalow', 'Camper/RV',
       'Entire home/apt', 'Entire vacation home', 'Entire bungalow',
       'Private room in hut', 'Entire villa', 'Private room in chalet',
       'Private room in camper/rv', 'Shared room in townhouse', 'Floor',
       'Earthen home', 'Private room in hostel',
       'Shared room in serviced apartment', 'Shared room in hostel',
       'Private room in lighthouse', 'Private room in floor',
       'Shared room in villa', 'Room in hostel', 'Private room in cabin',
       'Private room in island', 'Barn', 'Entire chalet',
       'Shared room in farm stay', 'Shared room in bus',
       'Shared room in guesthouse', 'Room in hotel',
       'Private room in tiny home', 'Campsite',
       'Private room in farm stay', 'Shared room in guest suite',
       'Religious building', 'Shared room in boutique hotel',
       'Private room in earthen home', 'Private room in treehouse', 'Hut',
       'Private room in boat', 'Room in rental unit',
       "Private room in shepherd's hut", 'Private room in castle',
       'Shared room in bed and breakfast', 'Dome', 'Tent',
       'Shared room in hotel', 'Private room in nature lodge',
       'Private room in religious building', 'Minsu', 'Casa particular',
       'Riad', 'Island', 'Castle', 'Tower',
       'Shared room in vacation home', 'Farm stay', 'Shipping container',
       'Treehouse', 'Private room in shipping container',
       'Shared room in tent'], dtype=object)

In [15]:
print(london_lists.property_type.nunique())
print(london_lists.property_type.isnull().sum())

99
0

In [16]:
print(london_lists.room_type.unique())
print()
print(london_lists.room_type.isnull().sum())

['Entire home/apt' 'Private room' 'Hotel room' 'Shared room']

0

* property_type 보다는 room_type이 그룹에 따른 인사이트를 얻기에 적합함

In [46]:
london_lists.amenities.unique()

array(['["Toaster", "Room-darkening shades", "Coffee maker: french press", "Wifi", "AC - split type ductless system", "Dishwasher", "Cleaning products", "Luggage dropoff allowed", "Dishes and silverware", "Hot water kettle", "Free dryer \\u2013 In unit", "Extra pillows and blankets", "Free washer \\u2013 In unit", "Hot water", "Kitchen", "Laundromat nearby", "Bathtub", "Clothing storage", "Wine glasses", "Central heating", "Bed linens", "Single level home", "Portable fans", "Microwave", "Private patio or balcony", "Essentials", "Freezer", "Iron", "Bosch stainless steel gas stove", "Refrigerator", "Hangers", "Cleaning available during stay", "Carbon monoxide alarm", "Coffee", "55\\" HDTV with Netflix, premium cable, standard cable", "Smoke alarm", "Long term stays allowed", "Dedicated workspace", "Cooking basics", "Paid parking off premises", "Hair dryer", "Dining table", "Ethernet connection", "Drying rack for clothing", "Oven", "Books and reading material"]',
       '["Toaster", "Room-darkening shades", "Shampoo", "Wifi", "Fire extinguisher", "Luggage dropoff allowed", "Dishes and silverware", "Hot water kettle", "Self check-in", "Extra pillows and blankets", "Free washer \\u2013 In unit", "Hot water", "Kitchen", "Baking sheet", "Blender", "Shower gel", "Children\\u2019s dinnerware", "Laundromat nearby", "Bathtub", "Stove", "Wine glasses", "Board games", "Body soap", "Central heating", "Babysitter recommendations", "Bed linens", "Lake access", "Portable fans", "Private patio or balcony", "Private entrance", "Essentials", "Clothing storage: dresser", "Paid street parking off premises", "Freezer", "Coffee maker", "Lock on bedroom door", "Iron", "Building staff", "Refrigerator", "Hangers", "Carbon monoxide alarm", "Coffee", "Smoke alarm", "Long term stays allowed", "First aid kit", "Dedicated workspace", "Cooking basics", "Outlet covers", "Children\\u2019s books and toys", "Hair dryer", "Dining table", "Ethernet connection", "Conditioner", "Oven", "Books and reading material"]',
       '["Shampoo", "Wifi", "Fire extinguisher", "Luggage dropoff allowed", "Dishes and silverware", "Heating", "Kitchen", "Hot water", "Microwave", "Essentials", "Washer", "Coffee maker", "Iron", "Host greets you", "TV with standard cable", "Refrigerator", "Hangers", "Dryer", "Carbon monoxide alarm", "Air conditioning", "Smoke alarm", "Long term stays allowed", "Dedicated workspace", "Cooking basics", "Hair dryer"]',
       ...,
       '["Paid parking on premises", "Carbon monoxide alarm", "TV", "Security cameras on property", "Wifi", "Smoke alarm", "Washer", "First aid kit", "Dedicated workspace", "Lock on bedroom door", "BBQ grill", "Kitchen", "Outdoor dining area"]',
       '["TV", "Shampoo", "Air conditioning", "Wifi", "Iron", "Bed linens", "Hair dryer", "Heating", "Hot water kettle"]',
       '["Crib", "Shampoo", "Wifi", "Dishwasher", "Fire extinguisher", "Dishes and silverware", "Hot water kettle", "Heating", "Extra pillows and blankets", "Kitchen", "High chair", "TV", "Stove", "Single level home", "Microwave", "Essentials", "Washer", "Coffee maker", "Elevator", "Iron", "Host greets you", "Refrigerator", "Hangers", "Patio or balcony", "Dryer", "Air conditioning", "Smoke alarm", "Long term stays allowed", "Cooking basics", "Hair dryer", "Oven"]'],
      dtype=object)

In [47]:
london_lists.amenities.nunique()

81129

* amenities는 유니크 값이 워낙 다양하게 있기 때문에 이 형태로는 사용하기 어려움

In [28]:
# 가격이 누락된 숙소 수 : 32,967개

london_lists.price.isnull().sum()

32967

### 리뷰 관련 컬럼

In [36]:
# 리뷰 전체 갯수의 null 값 = 0개
london_lists.number_of_reviews.isnull().sum()

0

In [37]:
# 리뷰 전체 개수가 0인 컬럼의 개수 = 24,983개

london_lists[london_lists.number_of_reviews == 0]

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
9,170524,https://www.airbnb.com/rooms/170524,20240319050633,2024-03-20,city scrape,STUNNING APT IN ST JAMES,NaN,NaN,https://a0.muscache.com/pictures/1077542/ba973...,194769,...,NaN,NaN,NaN,NaN,f,4,3,1,0,NaN
35,318986,https://www.airbnb.com/rooms/318986,20240319050633,2024-03-22,previous scrape,Central London flat for Olympics,NaN,NaN,https://a0.muscache.com/pictures/4746749/6bfa7...,1637212,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
45,42692,https://www.airbnb.com/rooms/42692,20240319050633,2024-03-22,previous scrape,Fabulous flat w garden and bkfst!,Holland Park/Notting Hill. Guests have access ...,The neighborhood of Holland Park borders Notti...,https://a0.muscache.com/pictures/239496/630e38...,186510,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
49,44384,https://www.airbnb.com/rooms/44384,20240319050633,2024-03-19,city scrape,DOUBLE ROOM IN A PENTHOUSE APARTMEN,A stunning double room with great views.<br />...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,194769,...,NaN,NaN,NaN,NaN,t,4,3,1,0,NaN
56,324055,https://www.airbnb.com/rooms/324055,20240319050633,2024-03-22,previous scrape,worth to stay.you will never regret,NaN,NaN,https://a0.muscache.com/pictures/3526645/f9c03...,1664001,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90847,1115272743905612628,https://www.airbnb.com/rooms/1115272743905612628,20240319050633,2024-03-19,city scrape,Primrose Hill Studio #25,A place to spread out in with extra wiggle roo...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,565833376,...,NaN,NaN,NaN,NaN,t,48,48,0,0,NaN
90848,1115272767893608505,https://www.airbnb.com/rooms/1115272767893608505,20240319050633,2024-03-19,city scrape,Primrose Hill Studio #27,"Two-storey living, unwind downstairs and rest ...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,565833376,...,NaN,NaN,NaN,NaN,t,48,48,0,0,NaN
90849,1115285644506865913,https://www.airbnb.com/rooms/1115285644506865913,20240319050633,2024-03-21,city scrape,Quad Bedroom with External Bathroom,The Chapter Hotels group had been in the hotel...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,444801189,...,NaN,NaN,NaN,NaN,t,33,10,23,0,NaN
90850,1115338006572763275,https://www.airbnb.com/rooms/1115338006572763275,20240319050633,2024-03-20,city scrape,Grosvenor Collection,This bright and spacious three-bedroom penthou...,"The area itself is a vibrant neighbourhood, of...",https://a0.muscache.com/pictures/prohost-api/H...,514234035,...,NaN,NaN,NaN,NaN,t,52,51,1,0,NaN
90851,1115347885713265376,https://www.airbnb.com/rooms/1115347885713265376,20240319050633,2024-03-19,city scrape,Comfy Home - Wood Green,Great for families and groups travelling toget...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,215155525,...,NaN,NaN,NaN,NaN,t,2,2,0,0,NaN

In [39]:
# 리뷰 스코어 레이팅 null 값 개수 확인 : 24,983개 
london_lists.review_scores_rating.isnull().sum()

24983

* 리뷰 스코어 레이팅 null 값 개수 = 리뷰가 0개인 숙소 수

In [40]:
# 리뷰 평점이 0인 숙소의 개수 : 4개
london_lists[london_lists.review_scores_rating == 0]

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
478,486501,https://www.airbnb.com/rooms/486501,20240319050633,2024-03-22,previous scrape,Bright 2 Bed Flat by Queens Park,Light and spacious 2 double bedroom flat next ...,NaN,https://a0.muscache.com/pictures/5781343/93d3e...,979982,...,5.0,4.0,3.0,NaN,t,1,1,0,0,0.01
856,698818,https://www.airbnb.com/rooms/698818,20240319050633,2024-03-22,previous scrape,Comfy Studio Private Garden/Kitchen,NaN,NaN,https://a0.muscache.com/pictures/9618563/79ad5...,3582753,...,5.0,5.0,4.0,NaN,f,1,1,0,0,0.01
982,760374,https://www.airbnb.com/rooms/760374,20240319050633,2024-03-22,previous scrape,London room for rent - good value!,I have a spare room in a small house.<br /><br...,I live in a residential area. My home is part ...,https://a0.muscache.com/pictures/10571364/d359...,4007960,...,NaN,NaN,NaN,NaN,f,1,0,1,0,0.01
20192,21845656,https://www.airbnb.com/rooms/21845656,20240319050633,2024-03-21,previous scrape,Comfortable apartment in central Chiswick,"Sole use of light, airy and comfortable apartm...",Leafy residential area yet only 25 minutes int...,https://a0.muscache.com/pictures/01d8135a-3aa4...,45795526,...,5.0,5.0,5.0,NaN,f,2,1,1,0,0.01

In [42]:
# 월 평균 리뷰 개수 컬럼의 null 값 확인 : 24,983개
london_lists['reviews_per_month'].isnull().sum()

24983

### 호스트가 운영하는 숙소 총 개수

In [44]:
# null값 개수 확인
london_lists.calculated_host_listings_count.isnull().sum()

0

In [45]:
london_lists.calculated_host_listings_count.describe()

count    90852.000000
mean        18.495927
std         65.205497
min          1.000000
25%          1.000000
50%          2.000000
75%          6.000000
max        558.000000
Name: calculated_host_listings_count, dtype: float64

In [49]:
london_lists.has_availability.unique()

array(['t', nan, 'f'], dtype=object)

In [ ]:
london_lists.has_availability.unique()