In [114]:
# 기본 패키지 불러오기 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
plt.style.use("seaborn")
sns.set(font_scale=1)
sns.set_style("whitegrid")

# 그래프를 노트북 안에 그리기 위해 설정
%matplotlib inline

# 맥 OS 폰트 깨짐 방지 코드
from matplotlib import rc
import matplotlib as mpl 
import matplotlib.font_manager as fm 

rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

## Inside Airbnb: London Data

### 데이터 불러오기

In [115]:
london_lists_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/listings.csv')
london_lists_summary_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/listings_outline.csv')
london_neighbourhoods_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/neighbourhoods.csv')
london_reviews_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/reviews.csv')
london_reviews_summary_raw = pd.read_csv('../../../../data_weekly/inside_airbnb/London/reviews_outline.csv')

In [116]:
london_lists = london_lists_raw.copy()
london_lists

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,312761,https://www.airbnb.com/rooms/312761,20240319050633,2024-03-21,city scrape,Spacious Central London Apartment by Hoxton Sq...,"Very central location, in the middle of Shored...",Everything is so convenient and the area is al...,https://a0.muscache.com/pictures/miso/Hosting-...,1608226,...,5.00,4.89,4.93,NaN,f,1,1,0,0,0.86
1,13913,https://www.airbnb.com/rooms/13913,20240319050633,2024-03-20,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.83,4.70,4.70,NaN,f,3,2,1,0,0.25
2,15400,https://www.airbnb.com/rooms/15400,20240319050633,2024-03-20,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.83,4.93,4.74,NaN,f,1,1,0,0,0.54
3,159736,https://www.airbnb.com/rooms/159736,20240319050633,2024-03-20,city scrape,A double Room 5mins from King's College Hospital,Calm sunny double room with a queen size bed a...,We love that in Loughborough Junction we live ...,https://a0.muscache.com/pictures/1067303/d2300...,766056,...,4.89,4.34,4.66,NaN,f,4,0,4,0,0.62
4,165336,https://www.airbnb.com/rooms/165336,20240319050633,2024-03-21,city scrape,Charming Flat in Notting Hill,A stylish apartment close to Portobello market...,"Notting Hill has many cafes, bars and restaura...",https://a0.muscache.com/pictures/60757460/47f8...,761400,...,4.96,4.87,4.71,NaN,f,1,1,0,0,1.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90847,1115272743905612628,https://www.airbnb.com/rooms/1115272743905612628,20240319050633,2024-03-19,city scrape,Primrose Hill Studio #25,A place to spread out in with extra wiggle roo...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,565833376,...,NaN,NaN,NaN,NaN,t,48,48,0,0,NaN
90848,1115272767893608505,https://www.airbnb.com/rooms/1115272767893608505,20240319050633,2024-03-19,city scrape,Primrose Hill Studio #27,"Two-storey living, unwind downstairs and rest ...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,565833376,...,NaN,NaN,NaN,NaN,t,48,48,0,0,NaN
90849,1115285644506865913,https://www.airbnb.com/rooms/1115285644506865913,20240319050633,2024-03-21,city scrape,Quad Bedroom with External Bathroom,The Chapter Hotels group had been in the hotel...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,444801189,...,NaN,NaN,NaN,NaN,t,33,10,23,0,NaN
90850,1115338006572763275,https://www.airbnb.com/rooms/1115338006572763275,20240319050633,2024-03-20,city scrape,Grosvenor Collection,This bright and spacious three-bedroom penthou...,"The area itself is a vibrant neighbourhood, of...",https://a0.muscache.com/pictures/prohost-api/H...,514234035,...,NaN,NaN,NaN,NaN,t,52,51,1,0,NaN
90851,1115347885713265376,https://www.airbnb.com/rooms/1115347885713265376,20240319050633,2024-03-19,city scrape,Comfy Home - Wood Green,Great for families and groups travelling toget...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,215155525,...,NaN,NaN,NaN,NaN,t,2,2,0,0,NaN

In [117]:
london_lists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90852 entries, 0 to 90851
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            90852 non-null  int64
 1   listing_url                                   90852 non-null  object
 2   scrape_id                                     90852 non-null  int64
 3   last_scraped                                  90852 non-null  object
 4   source                                        90852 non-null  object
 5   name                                          90852 non-null  object
 6   description                                   87851 non-null  object
 7   neighborhood_overview                         47521 non-null  object
 8   picture_url                                   90842 non-null  object
 9   host_id                                       90852 non-null  int64
 10  host_url                                      90852 non-null  object
 11  host_name                                     90847 non-null  object
 12  host_since                                    90847 non-null  object
 13  host_location                                 70566 non-null  object
 14  host_about                                    46814 non-null  object
 15  host_response_time                            57797 non-null  object
 16  host_response_rate                            57797 non-null  object
 17  host_acceptance_rate                          65213 non-null  object
 18  host_is_superhost                             90463 non-null  object
 19  host_thumbnail_url                            90847 non-null  object
 20  host_picture_url                              90847 non-null  object
 21  host_neighbourhood                            46955 non-null  object
 22  host_listings_count                           90847 non-null  float64
 23  host_total_listings_count                     90847 non-null  float64
 24  host_verifications                            90852 non-null  object
 25  host_has_profile_pic                          90847 non-null  object
 26  host_identity_verified                        90847 non-null  object
 27  neighbourhood                                 47522 non-null  object
 28  neighbourhood_cleansed                        90852 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      90852 non-null  float64
 31  longitude                                     90852 non-null  float64
 32  property_type                                 90852 non-null  object
 33  room_type                                     90852 non-null  object
 34  accommodates                                  90852 non-null  int64
 35  bathrooms                                     57894 non-null  float64
 36  bathrooms_text                                90722 non-null  object
 37  bedrooms                                      78118 non-null  float64
 38  beds                                          57837 non-null  float64
 39  amenities                                     90852 non-null  object
 40  price                                         57885 non-null  object
 41  minimum_nights                                90852 non-null  int64
 42  maximum_nights                                90852 non-null  int64
 43  minimum_minimum_nights                        90851 non-null  float64
 44  maximum_minimum_nights                        90851 non-null  float64
 45  minimum_maximum_nights                        90851 non-null  float64
 46  maximum_maximum_nights                        90851 non-null  float64
 47  minimum_nights_avg_ntm                        90851 non-null  float64
 48  maximum_nights_avg_ntm                        90851 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              86773 non-null  object
 51  availability_30                               90852 non-null  int64
 52  availability_60                               90852 non-null  int64
 53  availability_90                               90852 non-null  int64
 54  availability_365                              90852 non-null  int64
 55  calendar_last_scraped                         90852 non-null  object
 56  number_of_reviews                             90852 non-null  int64
 57  number_of_reviews_ltm                         90852 non-null  int64
 58  number_of_reviews_l30d                        90852 non-null  int64
 59  first_review                                  65869 non-null  object
 60  last_review                                   65869 non-null  object
 61  review_scores_rating                          65869 non-null  float64
 62  review_scores_accuracy                        65838 non-null  float64
 63  review_scores_cleanliness                     65843 non-null  float64
 64  review_scores_checkin                         65808 non-null  float64
 65  review_scores_communication                   65833 non-null  float64
 66  review_scores_location                        65808 non-null  float64
 67  review_scores_value                           65806 non-null  float64
 68  license                                       0 non-null      float64
 69  instant_bookable                              90852 non-null  object
 70  calculated_host_listings_count                90852 non-null  int64
 71  calculated_host_listings_count_entire_homes   90852 non-null  int64
 72  calculated_host_listings_count_private_rooms  90852 non-null  int64
 73  calculated_host_listings_count_shared_rooms   90852 non-null  int64
 74  reviews_per_month                             65869 non-null  float64
dtypes: float64(24), int64(17), object(34)
memory usage: 52.0+ MB

In [118]:
london_lists.columns.to_frame().reset_index(drop=True).rename(columns={0:'column name'}).to_csv('./NameofColumns_rawdata.csv')

### 분석에서 사용하지 않을 컬럼 삭제

In [119]:
london_lists.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [120]:
# 1차 선별한 컬럼 리스트 
# 1차 선별한 컬럼 27개 + 검증만 하고 삭제하기로 합의한 컬럼 3개('host_has_profile_pic','host_identity_verified', 'has_availability')
# 총 30개 컬럼 선별 

columns_selected = ['id', 'host_id', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_total_listings_count', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood_cleansed', \
    'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights', 'has_availability', 'number_of_reviews', 'number_of_reviews_l30d', 'review_scores_rating', 'review_scores_accuracy', \
    'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'reviews_per_month']
print(columns_selected)

['id', 'host_id', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_total_listings_count', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood_cleansed', 'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights', 'has_availability', 'number_of_reviews', 'number_of_reviews_l30d', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'reviews_per_month']

In [121]:
# 선별한 컬럼만 적용

london_lists = london_lists[columns_selected]
london_lists.head(10)

,id,host_id,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,...,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,312761,1608226,within a few hours,100%,98%,t,3.0,t,t,Hackney,...,122,0,4.96,4.97,4.93,4.96,5.00,4.89,4.93,0.86
1,13913,54730,within a few hours,86%,84%,t,5.0,t,t,Islington,...,41,0,4.80,4.73,4.73,4.75,4.83,4.70,4.70,0.25
2,15400,60302,within a day,100%,40%,f,1.0,t,t,Kensington and Chelsea,...,94,0,4.80,4.85,4.88,4.88,4.83,4.93,4.74,0.54
3,159736,766056,within an hour,100%,78%,t,5.0,t,t,Lambeth,...,96,0,4.72,4.79,4.66,4.75,4.89,4.34,4.66,0.62
4,165336,761400,within an hour,100%,92%,t,1.0,t,t,Kensington and Chelsea,...,237,2,4.74,4.88,4.79,4.94,4.96,4.87,4.71,1.57
5,313710,1612623,NaN,NaN,NaN,f,1.0,t,t,Brent,...,10,0,4.88,4.67,4.89,4.89,5.00,4.56,4.67,0.07
6,168359,648725,NaN,NaN,NaN,f,2.0,t,f,Southwark,...,9,0,4.63,4.75,4.63,4.88,4.88,4.13,4.75,0.06
7,17402,67564,within an hour,100%,96%,t,32.0,t,t,Westminster,...,56,0,4.77,4.83,4.72,4.72,4.72,4.89,4.61,0.35
8,24328,41759,NaN,NaN,0%,f,3.0,t,t,Wandsworth,...,94,0,4.90,4.89,4.91,4.90,4.93,4.59,4.65,0.58
9,170524,194769,within a day,67%,50%,f,9.0,t,t,Westminster,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [122]:
london_lists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90852 entries, 0 to 90851
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           90852 non-null  int64
 1   host_id                      90852 non-null  int64
 2   host_response_time           57797 non-null  object
 3   host_response_rate           57797 non-null  object
 4   host_acceptance_rate         65213 non-null  object
 5   host_is_superhost            90463 non-null  object
 6   host_total_listings_count    90847 non-null  float64
 7   host_has_profile_pic         90847 non-null  object
 8   host_identity_verified       90847 non-null  object
 9   neighbourhood_cleansed       90852 non-null  object
 10  room_type                    90852 non-null  object
 11  accommodates                 90852 non-null  int64
 12  bathrooms                    57894 non-null  float64
 13  bedrooms                     78118 non-null  float64
 14  beds                         57837 non-null  float64
 15  amenities                    90852 non-null  object
 16  price                        57885 non-null  object
 17  minimum_nights               90852 non-null  int64
 18  maximum_nights               90852 non-null  int64
 19  has_availability             86773 non-null  object
 20  number_of_reviews            90852 non-null  int64
 21  number_of_reviews_l30d       90852 non-null  int64
 22  review_scores_rating         65869 non-null  float64
 23  review_scores_accuracy       65838 non-null  float64
 24  review_scores_cleanliness    65843 non-null  float64
 25  review_scores_checkin        65808 non-null  float64
 26  review_scores_communication  65833 non-null  float64
 27  review_scores_location       65808 non-null  float64
 28  review_scores_value          65806 non-null  float64
 29  reviews_per_month            65869 non-null  float64
dtypes: float64(12), int64(7), object(11)
memory usage: 20.8+ MB

In [123]:
# 컬럼명 통일 

london_lists = london_lists.rename(columns={
    'id': '숙소_id',
    'host_id': '호스트_id',
    'host_response_time': '답변_평균시간',
    'host_response_rate': '문의_응답률',
    'host_acceptance_rate': '예약_수락률',
    'host_is_superhost': '슈퍼호스트',
    'host_total_listings_count': '숙소_수',
    'host_has_profile_pic' : '프로필_사진',
    'host_identity_verified' : '호스트_신원',
    'neighbourhood_cleansed': '숙소_지역',
    'room_type': '숙소_유형',
    'accommodates': '수용_인원수',
    'bathrooms': '욕실수',
    'bedrooms': '침실수',
    'beds': '침대수',
    'amenities': '편의시설',
    'price': '숙소_가격',
    'minimum_nights': '최소_숙박일',
    'maximum_nights': '최대_숙박일',
    'has_availability' : '예약_가능여부',
    'number_of_reviews': '리뷰수',
    'number_of_reviews_l30d': '30일_리뷰수',
    'review_scores_rating': '리뷰점수',
    'review_scores_accuracy': '숙소_정확성_리뷰점수',
    'review_scores_cleanliness': '숙소_청결도_리뷰점수',
    'review_scores_checkin': '숙소_체크인_리뷰점수',
    'review_scores_communication': '숙소_소통_리뷰점수',
    'review_scores_location': '숙소_위치_리뷰점수',
    'review_scores_value': '숙소_가격_리뷰점수',
    'reviews_per_month': '평균_리뷰수'
})

In [124]:
london_lists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90852 entries, 0 to 90851
Data columns (total 30 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   숙소_id        90852 non-null  int64
 1   호스트_id       90852 non-null  int64
 2   답변_평균시간      57797 non-null  object
 3   문의_응답률       57797 non-null  object
 4   예약_수락률       65213 non-null  object
 5   슈퍼호스트        90463 non-null  object
 6   숙소_수         90847 non-null  float64
 7   프로필_사진       90847 non-null  object
 8   호스트_신원       90847 non-null  object
 9   숙소_지역        90852 non-null  object
 10  숙소_유형        90852 non-null  object
 11  수용_인원수       90852 non-null  int64
 12  욕실수          57894 non-null  float64
 13  침실수          78118 non-null  float64
 14  침대수          57837 non-null  float64
 15  편의시설         90852 non-null  object
 16  숙소_가격        57885 non-null  object
 17  최소_숙박일       90852 non-null  int64
 18  최대_숙박일       90852 non-null  int64
 19  예약_가능여부      86773 non-null  object
 20  리뷰수          90852 non-null  int64
 21  30일_리뷰수      90852 non-null  int64
 22  리뷰점수         65869 non-null  float64
 23  숙소_정확성_리뷰점수  65838 non-null  float64
 24  숙소_청결도_리뷰점수  65843 non-null  float64
 25  숙소_체크인_리뷰점수  65808 non-null  float64
 26  숙소_소통_리뷰점수   65833 non-null  float64
 27  숙소_위치_리뷰점수   65808 non-null  float64
 28  숙소_가격_리뷰점수   65806 non-null  float64
 29  평균_리뷰수       65869 non-null  float64
dtypes: float64(12), int64(7), object(11)
memory usage: 20.8+ MB

### 정형 데이터 내 좋은 숙소의 기준
* 슈퍼호스트는 좋은 숙소의 기준에 부합할까? 

슈퍼호스트 기준
1. 숙박 10건 이상 호스팅 또는 3건의 예약에 걸쳐 총 100박 이상 호스팅
2. 응답률 90% 이상 유지
3. 예약 취소율 1% 미만 유지. 단, 정상참작이 가능한 상황에 따른 예약 취소는 제외
4. 전체 평점 4.8점 이상 유지(후기 작성 기한인 14일이 지나거나, 그전에라도 게스트와 호스트 양측이 모두 후기를 제출하면 후기는 슈퍼호스트 실적에 계산됩니다).

Q. 정형 데이터를 통해 머신러닝을 돌리는게 프로젝트 평가 항목 중 하나
* 우리가 잡은 주제 내에서 무슨 예측을 어떤 형태로 해야할지도 고민해야함

# 결측치

### 답변_평균시간

In [125]:
london_lists['답변_평균시간'].unique()

array(['within a few hours', 'within a day', 'within an hour', nan,
       'a few days or more'], dtype=object)

In [126]:
london_lists['답변_평균시간'].isnull().sum()

33055

In [127]:
london_lists['답변_평균시간'].value_counts()

within an hour        38118
within a few hours     9620
within a day           6757
a few days or more     3302
Name: 답변_평균시간, dtype: int64

In [128]:
# 답변 평균 시간 컬럼 제거 
# >> 좋은 숙소의 조건 가설로 잡은 슈퍼호스트 기준과 무관 
# >> 제외시키고 추후에 검증만 하기로 

london_lists.drop(columns='답변_평균시간', inplace=True)

In [129]:
london_lists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90852 entries, 0 to 90851
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   숙소_id        90852 non-null  int64
 1   호스트_id       90852 non-null  int64
 2   문의_응답률       57797 non-null  object
 3   예약_수락률       65213 non-null  object
 4   슈퍼호스트        90463 non-null  object
 5   숙소_수         90847 non-null  float64
 6   프로필_사진       90847 non-null  object
 7   호스트_신원       90847 non-null  object
 8   숙소_지역        90852 non-null  object
 9   숙소_유형        90852 non-null  object
 10  수용_인원수       90852 non-null  int64
 11  욕실수          57894 non-null  float64
 12  침실수          78118 non-null  float64
 13  침대수          57837 non-null  float64
 14  편의시설         90852 non-null  object
 15  숙소_가격        57885 non-null  object
 16  최소_숙박일       90852 non-null  int64
 17  최대_숙박일       90852 non-null  int64
 18  예약_가능여부      86773 non-null  object
 19  리뷰수          90852 non-null  int64
 20  30일_리뷰수      90852 non-null  int64
 21  리뷰점수         65869 non-null  float64
 22  숙소_정확성_리뷰점수  65838 non-null  float64
 23  숙소_청결도_리뷰점수  65843 non-null  float64
 24  숙소_체크인_리뷰점수  65808 non-null  float64
 25  숙소_소통_리뷰점수   65833 non-null  float64
 26  숙소_위치_리뷰점수   65808 non-null  float64
 27  숙소_가격_리뷰점수   65806 non-null  float64
 28  평균_리뷰수       65869 non-null  float64
dtypes: float64(12), int64(7), object(10)
memory usage: 20.1+ MB

### 문의_응답률

In [130]:
# 문의_응답률 컬럼 

london_lists['문의_응답률'].isnull().sum()

33055

In [131]:
# 문의 응답률이 not null값인 숙소 >> 에어비앤비 사이트에서 샘플 확인

condition_response_notnull = london_lists['문의_응답률'].notnull()
london_lists_raw[condition_response_notnull][['listing_url', 'name', 'host_response_rate']][:30]

# >> 사이트 숙소 상세 설명 페이지 내 문의 응답률 위치 확인

,listing_url,name,host_response_rate
0,https://www.airbnb.com/rooms/312761,Spacious Central London Apartment by Hoxton Sq...,100%
1,https://www.airbnb.com/rooms/13913,Holiday London DB Room Let-on going,86%
2,https://www.airbnb.com/rooms/15400,Bright Chelsea Apartment. Chelsea!,100%
3,https://www.airbnb.com/rooms/159736,A double Room 5mins from King's College Hospital,100%
4,https://www.airbnb.com/rooms/165336,Charming Flat in Notting Hill,100%
7,https://www.airbnb.com/rooms/17402,Fab 3-Bed/2 Bath & Wifi: Trendy W1,100%
9,https://www.airbnb.com/rooms/170524,STUNNING APT IN ST JAMES,67%
10,https://www.airbnb.com/rooms/314164,Comfy Family Home in London,0%
14,https://www.airbnb.com/rooms/34935,Bright 1 Bedroom Apartment w 2 beds Brick Lane,96%
15,https://www.airbnb.com/rooms/36299,Kew Gardens 3BR house in cul-de-sac,100%
16,https://www.airbnb.com/rooms/173082,The Residential Suite Above Gallery,100%
17,https://www.airbnb.com/rooms/174132,Large Bedroom with EnSuite Bathroom,100%
19,https://www.airbnb.com/rooms/315238,Stylish 2 bedroom London flat,100%
21,https://www.airbnb.com/rooms/316137,Double Room by Camden Market,97%
22,https://www.airbnb.com/rooms/36660,You are GUARANTEED to love this,100%
23,https://www.airbnb.com/rooms/316864,Trendy London Apartment,100%
24,https://www.airbnb.com/rooms/38610,CHARMING FAMILY HOME,100%
25,https://www.airbnb.com/rooms/38950,Room 1 Large Double Bedroom - front ground floor,33%
26,https://www.airbnb.com/rooms/38995,SPACIOUS ROOM IN CONTEMPORARY STYLE FLAT,100%
27,https://www.airbnb.com/rooms/178519,Newly refurbished 2-bed apartment,100%
29,https://www.airbnb.com/rooms/181664,Stunning 2 bedroom Fulham Riverside Flat Free ...,100%
30,https://www.airbnb.com/rooms/318287,safe and spacious room in comfy family home,100%
31,https://www.airbnb.com/rooms/182802,Quiet Double Room - Good for walks,100%
33,https://www.airbnb.com/rooms/41445,2 Double bed apartment in quiet area North London,100%
34,https://www.airbnb.com/rooms/183128,Private bathroom & spacious double room,100%
37,https://www.airbnb.com/rooms/320629,Hotel-style room in Camden Town,100%
38,https://www.airbnb.com/rooms/41712,"Room with a view, shared flat, central Bankside",100%
41,https://www.airbnb.com/rooms/198258,Penthouse Living in East London,100%
42,https://www.airbnb.com/rooms/321411,Fantastic location Double room,100%
43,https://www.airbnb.com/rooms/198279,London Whitechapel Room with WIFI,100%

응답률이 나와있는 숙소도 현재 사이트 내 문의 응답률과 다른 경우도 있음 
* https://www.airbnb.com/rooms/170524
* 66% > 33 %

In [132]:
# 문의 응답률이 null값인 숙소 >> 에어비앤비 사이트에서 샘플 확인

condition_response_null = london_lists['문의_응답률'].isnull()
london_lists_raw[condition_response_null][['listing_url', 'name']]

,listing_url,name
5,https://www.airbnb.com/rooms/313710,Pretty Home Kensal Green NW10 1 bed
6,https://www.airbnb.com/rooms/168359,Stunning 2 Bed Apartment in Elephant & Castle
8,https://www.airbnb.com/rooms/24328,"Battersea live/work artist house, garden communal"
11,https://www.airbnb.com/rooms/170702,A Double Room with River Views
12,https://www.airbnb.com/rooms/33332,Beautiful Ensuite Richmond-upon-Thames borough
...,...,...
90844,https://www.airbnb.com/rooms/1115272705566417319,Primrose Hill Studio #29
90845,https://www.airbnb.com/rooms/1115272736222611647,Primrose Hill Studio #28
90846,https://www.airbnb.com/rooms/1115272737028206976,Primrose Hill Studio #26
90847,https://www.airbnb.com/rooms/1115272743905612628,Primrose Hill Studio #25
90848,https://www.airbnb.com/rooms/1115272767893608505,Primrose Hill Studio #27

문의 응답률이 null값'인 숙소의 경우의 수 (가설)

1. 숙소 이용이 없어서 문의 또한 없기 때문에
2. 실제로 문의 응답을 안하는 경우 (카운팅을 하지 못하기 때문)

<br />

3. 에어비앤비 호스트 정보에 문의 응답률이 누락된 경우 
4. 데이터를 가져오면서 누락된 경우 및 기타 오류

In [133]:
# 문의 응답률이 null 값인 숙소의 리뷰수와 리뷰 점수 조회
# 실제로 문의가

london_lists[condition_response_null][['리뷰수', '리뷰점수']]
london_lists[condition_response_null][['리뷰수', '리뷰점수']].sort_values(by='리뷰수', ascending=False)

       리뷰수  리뷰점수
6874   711  4.87
885    575  4.95
1144   559  4.89
536    548  4.60
967    400  4.63
...    ...   ...
25321    0   NaN
25322    0   NaN
25334    0   NaN
25340    0   NaN
90848    0   NaN

[33055 rows x 2 columns]

리뷰가 많은데 문의 응답이 없는 경우가 있네?
* 이 케이스가 어떤 케이스인지 실제 사이트에서 확인해보자

In [134]:
london_lists_raw[condition_response_null][['listing_url', 'name']].shape

(33055, 2)

In [135]:
london_lists_raw[condition_response_null][['listing_url', 'name', 'number_of_reviews', 'review_scores_rating']].sort_values(by='number_of_reviews', ascending=False)[:30]

,listing_url,name,number_of_reviews,review_scores_rating
6874,https://www.airbnb.com/rooms/9046849,"Near HEATHROW AIRPORT, London, double room.",711,4.87
885,https://www.airbnb.com/rooms/877864,Bright guest room in gay household,575,4.95
1144,https://www.airbnb.com/rooms/1296836,"Covent Garden Flat Listed Building, London.",559,4.89
536,https://www.airbnb.com/rooms/502190,Large Double room private bath near Kilburn tube,548,4.60
967,https://www.airbnb.com/rooms/756481,Brand new studio in Victoria 15A,400,4.63
4030,https://www.airbnb.com/rooms/5878880,INDEPENDENT COSY LITTLE HOUSE IN CENTRAL LONDON,397,4.86
20,https://www.airbnb.com/rooms/315658,Double Room nr Oval Vauxhall Tubes,389,4.75
1087,https://www.airbnb.com/rooms/1117720,Central London: Sunny single room!,369,4.75
8819,https://www.airbnb.com/rooms/11226035,Tranquil comfortable single bedroom/females only,357,4.91
13151,https://www.airbnb.com/rooms/15855571,"LHR,free travelzone,UB35BD vPrivate,vClean,Gar...",354,4.91
8593,https://www.airbnb.com/rooms/10833014,"Charming apartment, Central London",350,4.70
317,https://www.airbnb.com/rooms/397504,Casa Chelsea,336,4.96
804,https://www.airbnb.com/rooms/715564,Brand new studio in Victoria 8A,332,4.70
841,https://www.airbnb.com/rooms/726669,Brand new studio in Victoria 11A,330,4.68
9876,https://www.airbnb.com/rooms/12444228,Room close to Central London - Wi-Fi and TV inc.,329,4.73
825,https://www.airbnb.com/rooms/720633,"Double studio + patio, Victoria 2A",328,4.54
985,https://www.airbnb.com/rooms/1044873,"Penthouse Room with Views over Park, near Station",308,4.87
840,https://www.airbnb.com/rooms/725370,Brand new studio in Victoria 12A,306,4.56
1322,https://www.airbnb.com/rooms/1626486,Private bathroom. Lovely area of North London N10,306,4.86
819,https://www.airbnb.com/rooms/717220,Double Studio in Victoria 5A,302,4.60
3560,https://www.airbnb.com/rooms/5041618,Pimlico Victoria Double Room Georgian Garden Flat,289,4.88
21757,https://www.airbnb.com/rooms/23367928,Charming Apartment in Central London - Farring...,289,4.81
3276,https://www.airbnb.com/rooms/4772751,Stylish 2 Bedroom Flat Central London *ZONE 1*,288,4.61
12087,https://www.airbnb.com/rooms/14521008,"Beautiful, Victorian Room Facing The Garden.",286,4.68
8993,https://www.airbnb.com/rooms/11419334,CAVENDISH Apartment+1,285,4.42
9372,https://www.airbnb.com/rooms/11966878,Large single room with a big cosy bed with ens...,281,4.89
1093,https://www.airbnb.com/rooms/1185611,Central London Zone1 Big Doubleroom,276,4.71
28981,https://www.airbnb.com/rooms/32440623,Double room in Islington N1,275,4.70
8546,https://www.airbnb.com/rooms/10706762,Clean and quite room with a garden,273,4.62
21652,https://www.airbnb.com/rooms/23335713,Master bedroom near Heathrow with an en-suite,270,4.64

슈퍼호스트가 아닌 경우 문의 응답률이 호스트 정보에 나오질 않나? 
*  확인 필요

슈퍼호스트 컬럼 확인

In [136]:
# 슈퍼호스트 컬럼 null값 확인 
london_lists_raw['host_is_superhost'].isnull().sum()

389

In [137]:
# 슈퍼호스트 컬럼 유니크값 확인 
london_lists_raw['host_is_superhost'].unique()

array(['t', 'f', nan], dtype=object)

In [138]:
# 슈퍼호스트 컬럼 값별 개수 확인
# 슈퍼호스트 값이 t : 14,251
# 슈퍼호스트 값이 f : 76,212

condition_superhost_t = london_lists_raw['host_is_superhost'] == 't'
condition_superhost_f = london_lists_raw['host_is_superhost'] == 'f'
print('슈퍼호스트인 숙소 ')
print(london_lists_raw[condition_superhost_t].shape)
print()
print('슈퍼호스트가 아닌 숙소')
print(london_lists_raw[condition_superhost_f].shape)

슈퍼호스트인 숙소
(14251, 75)

슈퍼호스트가 아닌 숙소
(76212, 75)

* 문의응답률 null 값 개수 : 33,055 개
* 슈퍼호스트가 아닌 숙소 : 76,212 개

<br />

*  슈퍼호스트가 아닌 경우에도 응답률 수집이 가능하긴 함!

리뷰가 많은데 문의응답률이 null값인 숙소의 슈퍼호스트 여부 확인

In [139]:
london_lists_raw[condition_response_null]['host_is_superhost'].unique()

array(['f', 't', nan], dtype=object)

In [140]:
london_lists_raw[condition_response_null][['listing_url', 'name', 'number_of_reviews', 'review_scores_rating', 'host_is_superhost']].sort_values(by='number_of_reviews', ascending=False)[:50]

,listing_url,name,number_of_reviews,review_scores_rating,host_is_superhost
6874,https://www.airbnb.com/rooms/9046849,"Near HEATHROW AIRPORT, London, double room.",711,4.87,f
885,https://www.airbnb.com/rooms/877864,Bright guest room in gay household,575,4.95,f
1144,https://www.airbnb.com/rooms/1296836,"Covent Garden Flat Listed Building, London.",559,4.89,f
536,https://www.airbnb.com/rooms/502190,Large Double room private bath near Kilburn tube,548,4.60,f
967,https://www.airbnb.com/rooms/756481,Brand new studio in Victoria 15A,400,4.63,f
4030,https://www.airbnb.com/rooms/5878880,INDEPENDENT COSY LITTLE HOUSE IN CENTRAL LONDON,397,4.86,f
20,https://www.airbnb.com/rooms/315658,Double Room nr Oval Vauxhall Tubes,389,4.75,f
1087,https://www.airbnb.com/rooms/1117720,Central London: Sunny single room!,369,4.75,f
8819,https://www.airbnb.com/rooms/11226035,Tranquil comfortable single bedroom/females only,357,4.91,f
13151,https://www.airbnb.com/rooms/15855571,"LHR,free travelzone,UB35BD vPrivate,vClean,Gar...",354,4.91,f
8593,https://www.airbnb.com/rooms/10833014,"Charming apartment, Central London",350,4.70,f
317,https://www.airbnb.com/rooms/397504,Casa Chelsea,336,4.96,f
804,https://www.airbnb.com/rooms/715564,Brand new studio in Victoria 8A,332,4.70,f
841,https://www.airbnb.com/rooms/726669,Brand new studio in Victoria 11A,330,4.68,f
9876,https://www.airbnb.com/rooms/12444228,Room close to Central London - Wi-Fi and TV inc.,329,4.73,t
825,https://www.airbnb.com/rooms/720633,"Double studio + patio, Victoria 2A",328,4.54,f
985,https://www.airbnb.com/rooms/1044873,"Penthouse Room with Views over Park, near Station",308,4.87,f
840,https://www.airbnb.com/rooms/725370,Brand new studio in Victoria 12A,306,4.56,f
1322,https://www.airbnb.com/rooms/1626486,Private bathroom. Lovely area of North London N10,306,4.86,f
819,https://www.airbnb.com/rooms/717220,Double Studio in Victoria 5A,302,4.60,f
3560,https://www.airbnb.com/rooms/5041618,Pimlico Victoria Double Room Georgian Garden Flat,289,4.88,t
21757,https://www.airbnb.com/rooms/23367928,Charming Apartment in Central London - Farring...,289,4.81,f
3276,https://www.airbnb.com/rooms/4772751,Stylish 2 Bedroom Flat Central London *ZONE 1*,288,4.61,t
12087,https://www.airbnb.com/rooms/14521008,"Beautiful, Victorian Room Facing The Garden.",286,4.68,f
8993,https://www.airbnb.com/rooms/11419334,CAVENDISH Apartment+1,285,4.42,f
9372,https://www.airbnb.com/rooms/11966878,Large single room with a big cosy bed with ens...,281,4.89,f
1093,https://www.airbnb.com/rooms/1185611,Central London Zone1 Big Doubleroom,276,4.71,f
28981,https://www.airbnb.com/rooms/32440623,Double room in Islington N1,275,4.70,f
8546,https://www.airbnb.com/rooms/10706762,Clean and quite room with a garden,273,4.62,f
21652,https://www.airbnb.com/rooms/23335713,Master bedroom near Heathrow with an en-suite,270,4.64,f
199,https://www.airbnb.com/rooms/358360,Room w/ WI-FI in Arty Victorian,266,4.79,f
273,https://www.airbnb.com/rooms/381467,Earls Court-London-2 Bed/2 Bath,265,4.66,f
8505,https://www.airbnb.com/rooms/10546640,Cosy Room in Central Apartment,262,4.71,f
6364,https://www.airbnb.com/rooms/8127220,Sunny room (on left) in renovated 1825 house,260,4.96,f
1999,https://www.airbnb.com/rooms/2841245,A single room in a large flat,258,4.74,f
869,https://www.airbnb.com/rooms/739774,Ensuite Studio in Victoria 6A,256,4.65,f
5010,https://www.airbnb.com/rooms/6843786,Highbury Garden House - King Room,254,4.84,f
844,https://www.airbnb.com/rooms/726950,Studio with private terrace near Victoria 9A,252,4.62,f
13573,https://www.airbnb.com/rooms/16256750,"Flat2(Angie), double room, London, Kings Cross",251,4.39,f
12824,https://www.airbnb.com/rooms/15333989,"Double bedroom, own bath and kitchen in Islington",250,4.75,f
777,https://www.airbnb.com/rooms/710203,Double studio in Victoria 4A,249,4.60,f
9999,https://www.airbnb.com/rooms/12613250,Lovely room on right in 1825 house,248,4.94,f
813,https://www.airbnb.com/rooms/717171,Cosy single studio in Victoria 14A,246,4.71,f
6062,https://www.airbnb.com/rooms/7876250,GuestReady - Self-Contained EnSuite Room w/Bal...,245,4.73,f
16802,https://www.airbnb.com/rooms/19455388,"Clean, comfortable double room",243,4.98,f
3629,https://www.airbnb.com/rooms/5081461,"Huge Attic Room, en-suite & terrace",242,4.96,f
871,https://www.airbnb.com/rooms/739825,Brand new studio in Victoria 13A,239,4.68,f
20389,https://www.airbnb.com/rooms/21988961,Shoreditch High Street Haven,239,4.90,f
12015,https://www.airbnb.com/rooms/14239782,Lovely double room 1 stop from London Bridge.,239,4.67,f
4651,https://www.airbnb.com/rooms/6532498,Highbury Garden House - Queen Room,238,4.85,f

* 응답률 null값 중 리뷰가 많은 숙소는 슈퍼호스트가 아니다.'는 가설은 기각. 
* 응답률 null값 중 리뷰가 많은 숙소의 대부분의 경우 슈퍼호스트가 아니다.' 이거는 맞는거 같은데? 

<br />

* 우선 응답률 null 값을 처리하는 방법은 투 트랙으로 가는 것이 좋을 듯.
    1. 리뷰 수가 많은 숙소의 경우 평균 또는 중위수로 처리
    2. 리뷰 수가 없는 숙소의 경우는 삭제하는 것이 맞지 않을까?

근데 리뷰가 없는 애들은 분석할게 없으니까 먼저 정리하는게 맞지 않을까?

우선은 중위수랑 평균 먼저 봐보자.

In [141]:
# 문의 응답률 >> 타입 변경 >> float

london_lists['문의_응답률'] = london_lists['문의_응답률'].str.rstrip('%').astype('float')
london_lists['문의_응답률'].head()

0    100.0
1     86.0
2    100.0
3    100.0
4    100.0
Name: 문의_응답률, dtype: float64

In [142]:
london_lists['문의_응답률'].describe()

count    57797.000000
mean        91.930360
std         21.931639
min          0.000000
25%         98.000000
50%        100.000000
75%        100.000000
max        100.000000
Name: 문의_응답률, dtype: float64

응답률 > 호스트 단위로 측정됨 (에어비앤비 CS 문의)

슈퍼호스트인데 문의 응답률이 없는 경우는 무엇인가? (에어비앤비 CS 팀에서 답변은 어렵다고 함)

슈퍼호스트  > 호스트 아이디로 묶어서 숙소 별로 일치하는지도 확인해야